/*
 * Header-menu registry — keyed by HeaderToolbar item-id, value describes
 * the dropdown contents.  Auto-generated by a codegen script from a desktop
 * probe (27/05/2026).
 *
 * Hand-edits will be overwritten; re-run the codegen after a fresh probe.
 */
import type { TvIconName } from '../../../components/TvIcon';

export type HeaderMenuVariant = {
  id: string;
  label: string;
  iconName?: TvIconName | null;
  checked?: boolean;
};

export type HeaderMenuRow = {
  id: string;
  label: string;
  iconName?: TvIconName | null;
  hotkey?: string | null;
  /** TRUE when this is the currently-selected value (e.g. active chart type). */
  checked?: boolean;
  /** TRUE when the row is starred — surfaces a filled star in the menu and
   *  marks the interval as one shown inline on the header strip. */
  favorited?: boolean;
  /** TRUE when the row is greyed + non-interactive (e.g. "Save layout" when
   *  there are no unsaved changes). */
  disabled?: boolean;
  /** Inline tile-variants — layout-setup rows ("4 charts") expose 1-N
   *  layout choices that render as a row of mini-tiles after the label. */
  variants?: HeaderMenuVariant[];
};

export type HeaderMenuSection = { header?: string | null; items: HeaderMenuRow[] };

export type HeaderMenuDef = { width: number; sections: HeaderMenuSection[] };

export const HEADER_MENUS: Record<string, HeaderMenuDef> = {
  "chart-interval": {
    "width": 180,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "add-custom-interval-button",
            "label": "Add custom interval…",
            "iconName": "menu-chart-interval-add-custom-interval",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "1T",
            "label": "1 tick",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "10T",
            "label": "10 ticks",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "100T",
            "label": "100 ticks",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "1000T",
            "label": "1000 ticks",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "1S",
            "label": "1 second",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "5S",
            "label": "5 seconds",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "10S",
            "label": "10 seconds",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "15S",
            "label": "15 seconds",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "30S",
            "label": "30 seconds",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "45S",
            "label": "45 seconds",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "1",
            "label": "1 minute",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "2",
            "label": "2 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "3",
            "label": "3 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "4",
            "label": "4 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "5",
            "label": "5 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "10",
            "label": "10 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "15",
            "label": "15 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "30",
            "label": "30 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "45",
            "label": "45 minutes",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "60",
            "label": "1 hour",
            "iconName": null,
            "hotkey": null,
            "checked": true,
            "favorited": true
          },
          {
            "id": "120",
            "label": "2 hours",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "180",
            "label": "3 hours",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "240",
            "label": "4 hours",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "1D",
            "label": "1 day",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "1W",
            "label": "1 week",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "1M",
            "label": "1 month",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "3M",
            "label": "3 months",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "6M",
            "label": "6 months",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "12M",
            "label": "12 months",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "1R",
            "label": "1 range",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "10R",
            "label": "10 ranges",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "100R",
            "label": "100 ranges",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "1000R",
            "label": "1000 ranges",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  },
  "candles": {
    "width": 249,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "bar",
            "label": "Bars",
            "iconName": "menu-candles-bars",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "candle",
            "label": "Candles",
            "iconName": "menu-candles-candles",
            "hotkey": null,
            "checked": true,
            "favorited": false
          },
          {
            "id": "hollowCandle",
            "label": "Hollow candles",
            "iconName": "menu-candles-hollow-candles",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "volCandles",
            "label": "Volume candles",
            "iconName": "menu-candles-volume-candles",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "line",
            "label": "Line",
            "iconName": "menu-candles-line",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "lineWithMarkers",
            "label": "Line with markers",
            "iconName": "menu-candles-line-with-markers",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "stepline",
            "label": "Step line",
            "iconName": "menu-candles-step-line",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "area",
            "label": "Area",
            "iconName": "menu-candles-area",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "hlcArea",
            "label": "HLC area",
            "iconName": "menu-candles-hlc-area",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "baseline",
            "label": "Baseline",
            "iconName": "menu-candles-baseline",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "column",
            "label": "Columns",
            "iconName": "menu-candles-columns",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "hilo",
            "label": "High-low",
            "iconName": "menu-candles-high-low",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "volFootprint",
            "label": "Volume footprint",
            "iconName": "menu-candles-volume-footprint",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "tpo",
            "label": "Time price opportunity",
            "iconName": "menu-candles-time-price-opportunity",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "svp",
            "label": "Session volume profile",
            "iconName": "menu-candles-session-volume-profile",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "ha",
            "label": "Heikin Ashi",
            "iconName": "menu-candles-heikin-ashi",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "renko",
            "label": "Renko",
            "iconName": "menu-candles-renko",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "pb",
            "label": "Line break",
            "iconName": "menu-candles-line-break",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "kagi",
            "label": "Kagi",
            "iconName": "menu-candles-kagi",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "pnf",
            "label": "Point & figure",
            "iconName": "menu-candles-point-figure",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "range",
            "label": "Range",
            "iconName": "menu-candles-range",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  },
  "show-favorite-indicators": {
    "width": 314,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "adr---average-daily-range-by-mikec-aka-thescrutiniser",
            "label": "ADR% - Average Daily Range % by MikeC (AKA TheScrutiniser)",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "eps-sales",
            "label": "EPS & Sales",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "flag-finder",
            "label": "Flag Finder",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "float-daily-change-short",
            "label": "Float, Daily % Change & Short %",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "ideal-entry-point",
            "label": "Ideal Entry Point",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "market-smith-indicators",
            "label": "Market Smith Indicators",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "moving-average-ribbon",
            "label": "Moving Average Ribbon",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "mtf-emas",
            "label": "MTF EMAs",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "no-retrace-from-high",
            "label": "No Retrace From High",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "pivot-trendlines-with-breaks-hg",
            "label": "Pivot Trendlines with Breaks [HG]",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "previous-candle-high-and-low",
            "label": "Previous Candle High and Low",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "study---momentum-intraday-detector",
            "label": "Study - Momentum Intraday Detector",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "total-dollar-volume",
            "label": "Total Dollar Volume",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "volume-breakouts-v2",
            "label": "Volume Breakouts v2",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  },
  "indicator-templates": {
    "width": 352,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "indicators-action-menu-item",
            "label": "Save indicator template…",
            "iconName": "menu-indicator-templates-save-indicator-template",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "Swing",
            "label": "Swing",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "Scalping",
            "label": "Scalping",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "indicators-action-menu-item",
            "label": "Open template…",
            "iconName": "menu-indicator-templates-open-template",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  },
  "layout-setup": {
    "width": 428,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "layouts-list-item-s",
            "label": "1",
            "iconName": "menu-layout-setup-1",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-s",
                "label": "1",
                "iconName": "menu-layout-setup-1",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-2h",
            "label": "2",
            "iconName": "menu-layout-setup-2",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-2h",
                "label": "2h",
                "iconName": "menu-layout-setup-layouts-list-item-2h",
                "checked": false
              },
              {
                "id": "layouts-list-item-2v",
                "label": "2v",
                "iconName": "menu-layout-setup-layouts-list-item-2v",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-3h",
            "label": "3",
            "iconName": "menu-layout-setup-3",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-3h",
                "label": "3h",
                "iconName": "menu-layout-setup-layouts-list-item-3h",
                "checked": false
              },
              {
                "id": "layouts-list-item-3v",
                "label": "3v",
                "iconName": "menu-layout-setup-layouts-list-item-3v",
                "checked": false
              },
              {
                "id": "layouts-list-item-3s",
                "label": "3s",
                "iconName": "menu-layout-setup-layouts-list-item-3s",
                "checked": false
              },
              {
                "id": "layouts-list-item-3r",
                "label": "3r",
                "iconName": "menu-layout-setup-layouts-list-item-3r",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-1",
                "label": "2-1",
                "iconName": "menu-layout-setup-layouts-list-item-2-1",
                "checked": false
              },
              {
                "id": "layouts-list-item-1-2",
                "label": "1-2",
                "iconName": "menu-layout-setup-layouts-list-item-1-2",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-4",
            "label": "4",
            "iconName": "menu-layout-setup-4",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-4",
                "label": "4",
                "iconName": "menu-layout-setup-layouts-list-item-4",
                "checked": false
              },
              {
                "id": "layouts-list-item-4v",
                "label": "4v",
                "iconName": "menu-layout-setup-layouts-list-item-4v",
                "checked": false
              },
              {
                "id": "layouts-list-item-4h",
                "label": "4h",
                "iconName": "menu-layout-setup-layouts-list-item-4h",
                "checked": false
              },
              {
                "id": "layouts-list-item-4s",
                "label": "4s",
                "iconName": "menu-layout-setup-layouts-list-item-4s",
                "checked": false
              },
              {
                "id": "layouts-list-item-4s-l",
                "label": "4s-l",
                "iconName": "menu-layout-setup-layouts-list-item-4s-l",
                "checked": false
              },
              {
                "id": "layouts-list-item-1-3",
                "label": "1-3",
                "iconName": "menu-layout-setup-layouts-list-item-1-3",
                "checked": false
              },
              {
                "id": "layouts-list-item-3-1",
                "label": "3-1",
                "iconName": "menu-layout-setup-layouts-list-item-3-1",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-2-l",
                "label": "2-2-l",
                "iconName": "menu-layout-setup-layouts-list-item-2-2-l",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-2-r",
                "label": "2-2-r",
                "iconName": "menu-layout-setup-layouts-list-item-2-2-r",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-2",
                "label": "2-2",
                "iconName": "menu-layout-setup-layouts-list-item-2-2",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-1-4",
            "label": "5",
            "iconName": "menu-layout-setup-5",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-1-4",
                "label": "1-4",
                "iconName": "menu-layout-setup-layouts-list-item-1-4",
                "checked": false
              },
              {
                "id": "layouts-list-item-5h",
                "label": "5h",
                "iconName": "menu-layout-setup-layouts-list-item-5h",
                "checked": false
              },
              {
                "id": "layouts-list-item-5v",
                "label": "5v",
                "iconName": "menu-layout-setup-layouts-list-item-5v",
                "checked": false
              },
              {
                "id": "layouts-list-item-5s",
                "label": "5s",
                "iconName": "menu-layout-setup-layouts-list-item-5s",
                "checked": false
              },
              {
                "id": "layouts-list-item-5s-l",
                "label": "5s-l",
                "iconName": "menu-layout-setup-layouts-list-item-5s-l",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-3",
                "label": "2-3",
                "iconName": "menu-layout-setup-layouts-list-item-2-3",
                "checked": false
              },
              {
                "id": "layouts-list-item-3-2",
                "label": "3-2",
                "iconName": "menu-layout-setup-layouts-list-item-3-2",
                "checked": false
              },
              {
                "id": "layouts-list-item-4-1",
                "label": "4-1",
                "iconName": "menu-layout-setup-layouts-list-item-4-1",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-3-l",
                "label": "2-3-l",
                "iconName": "menu-layout-setup-layouts-list-item-2-3-l",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-3-r",
                "label": "2-3-r",
                "iconName": "menu-layout-setup-layouts-list-item-2-3-r",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-6",
            "label": "6",
            "iconName": "menu-layout-setup-6",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-6",
                "label": "6",
                "iconName": "menu-layout-setup-layouts-list-item-6",
                "checked": false
              },
              {
                "id": "layouts-list-item-6h",
                "label": "6h",
                "iconName": "menu-layout-setup-layouts-list-item-6h",
                "checked": false
              },
              {
                "id": "layouts-list-item-6v",
                "label": "6v",
                "iconName": "menu-layout-setup-layouts-list-item-6v",
                "checked": false
              },
              {
                "id": "layouts-list-item-6c",
                "label": "6c",
                "iconName": "menu-layout-setup-layouts-list-item-6c",
                "checked": false
              },
              {
                "id": "layouts-list-item-2-4",
                "label": "2-4",
                "iconName": "menu-layout-setup-layouts-list-item-2-4",
                "checked": false
              },
              {
                "id": "layouts-list-item-4-2",
                "label": "4-2",
                "iconName": "menu-layout-setup-layouts-list-item-4-2",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-4-3",
            "label": "7",
            "iconName": "menu-layout-setup-7",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-4-3",
                "label": "4-3",
                "iconName": "menu-layout-setup-layouts-list-item-4-3",
                "checked": false
              },
              {
                "id": "layouts-list-item-7h",
                "label": "7h",
                "iconName": "menu-layout-setup-layouts-list-item-7h",
                "checked": false
              },
              {
                "id": "layouts-list-item-7s",
                "label": "7s",
                "iconName": "menu-layout-setup-layouts-list-item-7s",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-8",
            "label": "8",
            "iconName": "menu-layout-setup-8",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-8",
                "label": "8",
                "iconName": "menu-layout-setup-layouts-list-item-8",
                "checked": false
              },
              {
                "id": "layouts-list-item-8c",
                "label": "8c",
                "iconName": "menu-layout-setup-layouts-list-item-8c",
                "checked": false
              },
              {
                "id": "layouts-list-item-8h",
                "label": "8h",
                "iconName": "menu-layout-setup-layouts-list-item-8h",
                "checked": false
              },
              {
                "id": "layouts-list-item-8v",
                "label": "8v",
                "iconName": "menu-layout-setup-layouts-list-item-8v",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-9s",
            "label": "9",
            "iconName": "menu-layout-setup-9",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-9s",
                "label": "9s",
                "iconName": "menu-layout-setup-layouts-list-item-9s",
                "checked": false
              },
              {
                "id": "layouts-list-item-5-4",
                "label": "5-4",
                "iconName": "menu-layout-setup-layouts-list-item-5-4",
                "checked": false
              },
              {
                "id": "layouts-list-item-9h",
                "label": "9h",
                "iconName": "menu-layout-setup-layouts-list-item-9h",
                "checked": false
              },
              {
                "id": "layouts-list-item-9v",
                "label": "9v",
                "iconName": "menu-layout-setup-layouts-list-item-9v",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-10c5",
            "label": "10",
            "iconName": "menu-layout-setup-10",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-10c5",
                "label": "10c5",
                "iconName": "menu-layout-setup-layouts-list-item-10c5",
                "checked": false
              },
              {
                "id": "layouts-list-item-10h",
                "label": "10h",
                "iconName": "menu-layout-setup-layouts-list-item-10h",
                "checked": false
              },
              {
                "id": "layouts-list-item-10v",
                "label": "10v",
                "iconName": "menu-layout-setup-layouts-list-item-10v",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-12c6",
            "label": "12",
            "iconName": "menu-layout-setup-12",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-12c6",
                "label": "12c6",
                "iconName": "menu-layout-setup-layouts-list-item-12c6",
                "checked": false
              },
              {
                "id": "layouts-list-item-12c4",
                "label": "12c4",
                "iconName": "menu-layout-setup-layouts-list-item-12c4",
                "checked": false
              },
              {
                "id": "layouts-list-item-12h",
                "label": "12h",
                "iconName": "menu-layout-setup-layouts-list-item-12h",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-14c7",
            "label": "14",
            "iconName": "menu-layout-setup-14",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-14c7",
                "label": "14",
                "iconName": "menu-layout-setup-14",
                "checked": false
              }
            ]
          },
          {
            "id": "layouts-list-item-16c8",
            "label": "16",
            "iconName": "menu-layout-setup-16",
            "hotkey": null,
            "checked": false,
            "favorited": false,
            "variants": [
              {
                "id": "layouts-list-item-16c8",
                "label": "16c8",
                "iconName": "menu-layout-setup-layouts-list-item-16c8",
                "checked": false
              },
              {
                "id": "layouts-list-item-16c4",
                "label": "16c4",
                "iconName": "menu-layout-setup-layouts-list-item-16c4",
                "checked": false
              }
            ]
          }
        ]
      }
    ]
  },
  "save-load-menu": {
    "width": 197,
    "sections": [
      {
        "header": null,
        "items": [
          {
            "id": "save-load-menu-item-save",
            "label": "Save layout",
            "iconName": null,
            "hotkey": "Ctrl + S",
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-auto-save",
            "label": "Autosave",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-sharing",
            "label": "Share layout",
            "iconName": "menu-manage-layouts-share-layout",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-clone",
            "label": "Make a copy",
            "iconName": "menu-manage-layouts-make-a-copy",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-rename",
            "label": "Rename",
            "iconName": "menu-manage-layouts-rename",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-download",
            "label": "Download chart data",
            "iconName": "menu-manage-layouts-download-chart-data",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "save-load-menu-item-create",
            "label": "Create new layout",
            "iconName": "menu-manage-layouts-create-new-layout",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "save-load-menu-item-recent",
            "label": "Daily INTC, 1D",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": true
          },
          {
            "id": "save-load-menu-item-recent",
            "label": "Intraday INTC, 60",
            "iconName": null,
            "hotkey": null,
            "checked": true,
            "favorited": true
          },
          {
            "id": "save-load-menu-item-recent",
            "label": "Study - Momentum AXTI, 1D",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "save-load-menu-item-recent",
            "label": "Swing Multi QQQ, 60",
            "iconName": null,
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      },
      {
        "header": null,
        "items": [
          {
            "id": "save-load-menu-item-load",
            "label": "Open layout",
            "iconName": "menu-manage-layouts-open-layout",
            "hotkey": "Dot",
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  },
  "take-a-snapshot": {
    "width": 250,
    "sections": [
      {
        "header": "CHART SNAPSHOT",
        "items": [
          {
            "id": "save-chart-image",
            "label": "Download image",
            "iconName": "menu-take-a-snapshot-download-image",
            "hotkey": "Ctrl + Alt + S",
            "checked": false,
            "favorited": false
          },
          {
            "id": "copy-chart-image",
            "label": "Copy image",
            "iconName": "menu-take-a-snapshot-copy-image",
            "hotkey": "Ctrl + Shift + S",
            "checked": false,
            "favorited": false
          },
          {
            "id": "copy-link-to-the-chart-image",
            "label": "Copy link",
            "iconName": "menu-take-a-snapshot-copy-link",
            "hotkey": "Alt + S",
            "checked": false,
            "favorited": false
          },
          {
            "id": "open-image-in-new-tab",
            "label": "Open in new tab",
            "iconName": "menu-take-a-snapshot-open-in-new-tab",
            "hotkey": null,
            "checked": false,
            "favorited": false
          },
          {
            "id": "tweet-chart-image",
            "label": "Tweet image",
            "iconName": "menu-take-a-snapshot-tweet-image",
            "hotkey": null,
            "checked": false,
            "favorited": false
          }
        ]
      }
    ]
  }
};
